name: Badges

on: push

jobs:
  make_badges:
    name: Make Coverage Badges
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test:c

      - name: Make Badges
        run: npm run make-badges

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.1.0